### ISSUE TITLE
Error with IPAD OSC

### ISSUE THREAD

**Issue by SmallTownSound** [chinenual/synergize#14] opened 2020-11-06 02:01 UTC
'Connected' and get this error in Voicing Mode:

Uncaught Exception:
Error: read ECONNRESET
at TCP.omSreamRead

This might be caused by 'ZeroConf' since I have to manually connect to both Synergia & OSC.  It there any troubleshooting or diags that can be run to find out if ZeroConf is corrupted .  Running win 10, newest update.  I did re-install Itunes, didn't help.

Don

**Comment by chinenual** [comment] 2020-11-06 14:52
Thanks for the bug report! 

Please send the `synergize.log` and let me know the approximate time that the error occured. 

The log is located at: `%APPDATA%\Synergize\synergize.log`

**Comment by chinenual** [comment] 2020-11-06 16:48
@SmallTownSound - in my testing on Windows, Bonjour/Zeroconf works reliably when configuring the OSC interface.  I have never managed to see it work for Synergia (on Windows).  Are you seeing Zeroconf problems only with Synergia or also with OSC? 

On MacOS, both are reliable (except for the issue mentioned in #13 )

**Comment by SmallTownSound** [comment] 2020-11-06 18:51
Neither work, so i'm sure it is a setup problem of some kind. I have done normal troubleshooting, to no avail... There has to be some kind of diagnostic available to see where the problem is.

**Comment by chinenual** [comment] 2020-11-06 18:57
You can try running a Bonjour browser (e.g.  http://hobbyistsoftware.com/bonjourbrowser) to see if either Synergize, Synergia or TouchOSC are registering on your Windows machine. 

In mean time I'd like to try to diagnose the connection reset you reported last night when connected manually - can you find the synergize.log?

**Comment by SmallTownSound** [comment] 2020-11-06 19:01
Searching for it now, so far not finding it, should have been done already with a ssd drive..  Where should it be located?

The error pops up as soon as I click on Voicing Mode button.

**Comment by chinenual** [comment] 2020-11-06 19:04
The log should be located at: `%APPDATA%\Synergize\synergize.log` (e.g., `C:\Users\yourusername\AppData\Roaming\Synergize\synergize.log` on Windows.   

`~/Library/Application\ Support/Synergize/synergize.log` on Mac.

**Comment by SmallTownSound** [comment] 2020-11-06 19:12
Running the browser finds the OSC.udp,   and if I toggle the VRAM button enough times, it finds synergis, but synergize still does not see Synergia  I don't see Synergize on the list.  Still no synergize.log

**Comment by SmallTownSound** [comment] 2020-11-06 19:17
error consistently comes up after I select voicing mode, it asks if ipad osc app is what I want, when I click OK, I get the error.

**Comment by SmallTownSound** [comment] 2020-11-06 19:18
[synergize.log](https://github.com/chinenual/synergize/files/5503064/synergize.log)

**Comment by chinenual** [comment] 2020-11-06 19:35
@SmallTownSound - thanks for the log!    

From initial inspection, it looks like Synergize is finding your iPad via bonjour.   I don't actually see the connection reset in the log - but from other errors, I'm wondering if there's actually some problem with the Synergize application communicating with the user interface (which is a Chrome-based Electron instance).  Weird! I've never seen this happen.   
Anything unusual about your Windows configuration?   What version of Windows are you running?  (`Settings -> System -> About -> Version`).  Any third party antivirus software?

I don't think it could be a firewall configuration issue - if it were you wouldn't see any Synergize UI at all.   

Sorry you are having problems!  This will take me some time to digest.

**Comment by SmallTownSound** [comment] 2020-11-06 19:45
Win10   Version 20H2     Turned off NOD32, no difference

**Comment by SmallTownSound** [comment] 2020-11-06 19:45
That is what beta testing is all about ;)

**Comment by chinenual** [comment] 2020-11-06 20:05
Next time this happens, please try to get a screenshot so I can see what you are seeing in the UI

**Comment by chinenual** [comment] 2020-11-06 20:29
OK - I misinterpreted what I was seeing in the logs.  It's not UI related.  I am seeing errors talking to your iPad. 

The error is `failed: lookup Dons-iPad: no such host` -- so this may in fact indicate some sort of flaky behavior with Bonjour resolving the iPad hostname on your Windows machine.  Can you try manually connecting to the iPad (in Synergize, `Zeroconf Control Surface` unchecked and manually specify the numeric IP address and port as displayed on the TouchOSC config on your iPad).

I also see `ERROR:  SendToUI failed to decode json response : accxyz 0: unexpected end of JSON input`.   (I'll need to review the error handling  to ensure Synergize handles this cleanly - I don't think they should be causing any noticable errors, but I've never specifically tested that configuration).   In the mean time, please turn off all options in TouchOSC's Options settings (accelorometer off, touch messages off, ping off, etc).   If turning them off improves the behavior, that's gives me more clues as to what is wrong.

**Comment by chinenual** [comment] 2020-11-07 01:27
While I havent exactly reproduced your error, I am able to reproduce the "failed to decode json response" for the OSC accelerometer traffic.  In my test, I was able to crash Synergize by flooding it with a lot of movement from the ipad.  I've logged that as #15.  Since that may not completely explain the CONN RESET you saw, I'm leaving this issue open pending further testing and analysis.

**Comment by SmallTownSound** [comment] 2020-11-07 03:44
Update as of tonight.  Working with software on laptop, instead of desktop.  Issues on laptop same as on desktop, both need zeroconf OFF to work, even though both synergia and touchosc show up in bonjour browser.

I don't to get any errors, synergize connects to both synergia, and touchOSC when I activate voicing mode.  Problem with this setup synergize doesn't update OSC, OSC shows everything on screen as when the first booted, nothing matches synergize voice layout.  NO interaction between the two. 
Don

**Comment by SmallTownSound** [comment] 2020-11-07 03:47
PS resetting the VRAM address every time is getting frustrating..  :(

**Comment by SmallTownSound** [comment] 2020-11-07 05:13
Went back to desktop, and actually got things to work, after a lot of reading and reconfiguring....  zeroconf off on synergia.... on for touchosc..  Do not know what is set differently...

Both connect, and works in voicing mode!!!!!!    On IPAD:Shows all OSCs, instead of just active, and Plus minus doesn't work correctly.  Not everything updates correctly, but switching between tabs seems to correct it.   Seems to update on either IPAD or PC, and they interact as they are supposed to, but with intermittent updating issues.

For the record, PC is hardwired to router, IPAD is wireless.  IPAD in a couple month old 7th gen, with latest OS, if that makes a difference.

all envelopes show , just like OSCs, plus all the knobs across bottom don't register on Ipad util they are touched.  Original settings don't seem to get sent on start of voicing mode.

Only real problem is Synergia becomes silent during voicing mode, which makes the whole thing rather pointless...

Do get periodic error dialog saying "lookup Don's-iPad: no such host...  click close and seems to have no effect.

The main thing is they are all SORT OF working now...  Time to go to bed...

**Comment by chinenual** [comment] 2020-11-07 12:52
> PS resetting the VRAM address every time is getting frustrating.. :(

Yes - the manual VST config is strictly a short term workaround while we work on making zeroconf work better, or find an alternate way to link the two applications.

**Comment by chinenual** [comment] 2020-11-07 12:59
> Do get periodic error dialog saying "lookup Don's-iPad: no such host... click close and seems to have no effect.

This likely explains the intermittent updates to TouchOSC.   Currently assuming this is all part of the "zeroconf not working properly on Windows" issues you are seeing.

> Only real problem is Synergia becomes silent during voicing mode, which makes the whole thing rather pointless...

The initial one-oscillator voice loaded at the start of voicing mode will be silent until / unless you adjust envelope settings. Easiest thing to do is to click on a library voice after entering Voicing mode -- then you can edit the existing voice settings rather than trying to build one up from first principles.    Synergize matches the old SYNCHS behavior here -- I debated with myself whether to load a different default voice for Voicing mode, but in the end decided to stay true to SYNCHS.  Open to different opinions!

**Comment by SmallTownSound** [comment] 2020-11-07 16:22
I see what is wrong, was pretty tired, should have went to bed an hour earlier  ;)

Would be nice for it to use current voice shown when going into voicing mode in GUI (double clicked on voice you want) , instead of starting from scratch, and having to search for the voice your were wanting to edit.  I think most users modify existing voices instead of starting from scratch.

Even when going to startup voice setting, or loaded voice, the IPAD doesn't show the proper elements like are shown on your web page under Control Surface, ALL are showing in all tabs  Only 4 should be shown in picture.

Still Very nice indeed!     Looking forward to working through problems.

![20201107_101639](https://user-images.githubusercontent.com/41487289/98446418-f7fa3600-20e2-11eb-9612-1bec2d9a9c81.jpg)

**Comment by chinenual** [comment] 2020-11-07 16:26
The only times I've seen this sort of failure to initialize the control surface is when I have a bad wifi connection on either my laptop or the ipad. (I have 3 access points in the house and sometimes the ipad latches on to one of the remote ones with a poor signal).  Any chance that is happening here?

**Comment by SmallTownSound** [comment] 2020-11-07 16:35
Only one router, desktop is wired and IPAD shows full speed connection.   Could it be newest IPAD OS?  I know everything breaks when apple releases a new OS...

**Comment by chinenual** [comment] 2020-11-07 16:37
Anything's possible- but that seems unlikely to be the root cause.

**Comment by SmallTownSound** [comment] 2020-11-07 16:41
I am open to any other diagnostic stuff you want me to run..  did computer service for a number of years, not the average user.

**Comment by chinenual** [comment] 2020-11-07 16:42
> Would be nice for it to use current voice shown when going into voicing mode in GUI (double clicked on voice you want) , instead of starting from scratch, and having to search for the voice your were wanting to edit. I think most users modify existing voices instead of starting from scratch.

I like this.  I've created an enhancement request as #17.

**Comment by chinenual** [comment] 2020-11-07 16:47
For this most recent failure to update the control surface, had you turned off the /accxyz, /z and /ping messages in TouchOSC?    There's a chance that the flood of accxyz messages somehow interferes with Synergize sending out the initialization messages.

**Comment by SmallTownSound** [comment] 2020-11-07 16:51
all are turned off..  Will try it wit my old ipad later today.

**Comment by SmallTownSound** [comment] 2020-11-07 17:46
Just tried it with old ipad, exact same things happen.

**Comment by chinenual** [comment] 2020-11-07 17:55
Drat.  So windows machine using wired network; ipads on same access point and show strong signal, yet some osc messages are getting lost.  Now that youve disabled the noisy /accxyz messages, can you send me a recent synergize.log so I can review and see if I can spot any other problems?

**Comment by SmallTownSound** [comment] 2020-11-07 18:11
[synergize.log](https://github.com/chinenual/synergize/files/5505253/synergize.log)

**Comment by chinenual** [comment] 2020-11-07 18:48
OK - I see you are still trying to use the bonjour config for OSC - and there are lots of errors int the log about name resolution for your ipad.  That can explain the failure to initialize the touchosc interface.  Until I get this sorted, please try disabling zeroconf even for the ipad - set the address and ports manually.   

Good news is that I've been able to reproduce the "failed: lookup Somebody-iPad: no such host" when I connect to mine with zeroconf.   

This just reenforces that zeroconf on Windows is not working reliably enough.

**Comment by SmallTownSound** [comment] 2020-11-07 18:51
Will Do....

**Comment by SmallTownSound** [comment] 2020-11-07 18:59
No change, not updating properly...    Will work on it later tonight...

**Comment by chinenual** [comment] 2020-11-07 19:02
> No change, not updating properly...

Oh no!  That works quite reliably for me -- when you do return to this, please send another log so i can see what's happening when you are not trying to use zeroconf.

**Comment by chinenual** [comment] 2020-11-07 19:02
Also: if you'd like a more direct way to chat/coordinate, please consider joining our Slack group.

**Comment by SmallTownSound** [comment] 2020-11-07 19:15
Hate slack, but will try it again.  How do I find the group

**Comment by chinenual** [comment] 2020-11-07 19:17
I just need an email address to send the invite.  You can send it to me at `support at chinenual.com`

**Comment by chinenual** [comment] 2020-12-07 22:07
Issues fixed via a number of fixes in 2.3.0.  Please open a new bug report if you experience any problems with OSC

**Closed as completed by chinenual** 2020-12-07 22:07 UTC
Labels: bug
